sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
  - "9"

install:
  - npm install -g truffle ganache-cli
  - nohup ganache-cli &
  - npm install
  - mv config/truffle.provider.example.js config/truffle.provider.js
script:
  - npm run lint
  - npm run contract:compile
  - npm run test

